[build]
  command = "pnpm install && pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "14"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  command = "pnpm install && pnpm build"

[build.environment]
NODE_VERSION = "20.9.0"

